"""
Refresh _data/github.yml from the GitHub API.

The theme originally rendered the repositories page with hotlinked cards from
github-readme-stats.vercel.app and github-profile-trophy.vercel.app. Both are
free public instances and both went down (503 DEPLOYMENT_PAUSED and 402
DEPLOYMENT_DISABLED respectively), taking every image on the page with them.

So the cards are now rendered by the site itself from data captured here. The
only runtime dependency left is avatars.githubusercontent.com.

Reads the user and repo lists from _data/repositories.yml, so that file stays
the single place to edit. Re-run after adding a repository, or to refresh the
star counts.

Run:  python3 scripts/fetch_github.py
Out:  _data/github.yml
"""

import json
import pathlib
import sys
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
API = "https://api.github.com"


def get(path):
    req = urllib.request.Request(
        API + path,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "hdclark94.github.io-build",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.load(r)
    except urllib.error.HTTPError as e:
        if e.code == 403:
            sys.exit("GitHub API rate limit hit (60/hr unauthenticated). Try later.")
        sys.exit(f"GitHub API {e.code} for {path}")


def yaml_str(value):
    if value is None:
        return '""'
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    src = (ROOT / "_data" / "repositories.yml").read_text()
    users, repos, section = [], [], None
    for line in src.splitlines():
        stripped = line.strip()
        if stripped.endswith(":") and not stripped.startswith("-"):
            section = stripped[:-1]
        elif stripped.startswith("- "):
            (users if section == "github_users" else repos).append(stripped[2:].strip())

    out = ["# Generated by scripts/fetch_github.py - do not edit by hand.", "users:"]
    for login in users:
        u = get(f"/users/{login}")
        out += [
            f"  - login: {yaml_str(u['login'])}",
            f"    name: {yaml_str(u.get('name') or u['login'])}",
            f"    avatar: {yaml_str(u['avatar_url'])}",
            f"    url: {yaml_str(u['html_url'])}",
            f"    bio: {yaml_str(u.get('bio'))}",
            f"    public_repos: {u.get('public_repos', 0)}",
            f"    followers: {u.get('followers', 0)}",
        ]
        print(f"user  {login}")

    out.append("repos:")
    for full in repos:
        r = get(f"/repos/{full}")
        out += [
            f"  - full_name: {yaml_str(r['full_name'])}",
            f"    name: {yaml_str(r['name'])}",
            f"    owner: {yaml_str(r['owner']['login'])}",
            f"    description: {yaml_str(r.get('description'))}",
            f"    language: {yaml_str(r.get('language'))}",
            f"    stars: {r.get('stargazers_count', 0)}",
            f"    forks: {r.get('forks_count', 0)}",
            f"    url: {yaml_str(r['html_url'])}",
        ]
        print(f"repo  {full}  ({r.get('stargazers_count', 0)} stars)")

    dest = ROOT / "_data" / "github.yml"
    dest.write_text("\n".join(out) + "\n")
    print("wrote", dest)


if __name__ == "__main__":
    main()
